apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Indamutsa/my-cd-argo.git
    targetRevision: HEAD
    path: example-app
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: example-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true # to overwrite direct applies in the server when they fail
      prune: true # To make sure argo cd delete stuff in the cluster as well when deleted on the repository